import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

const geistSans = Inter({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Inter({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});
export const metadata: Metadata = {
	title: "10 Mintue School",
	description: "Generated by create next app",
};
interface Props {
	children: ReactNode;
	params: Promise<{ lang: string }>;
}
export default async function RootLayout({ children, params }: Props): Promise<ReactNode> {
	const { lang } = await params;
	if (!lang) {
		throw new Error("Language not provided");
	}
	return (
		<html lang={lang}>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
